// ============================================================
//  src/screens/PrivacyPolicyScreen.js
//  Privacy Policy — Price and Stock Alert Application
//  Updated: April 2026
// ============================================================

import React from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, StatusBar,
} from 'react-native';
import { Ionicons }       from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Colors, FontSize, FontWeight, Spacing, Radius, Shadow } from '../constants/theme';

// ── Section Component ──────────────────────────────────────────────────────────
const Section = ({ icon, title, children }) => (
  <View style={styles.section}>
    <View style={styles.sectionHeader}>
      <View style={styles.sectionIconBox}>
        <Ionicons name={icon} size={18} color={Colors.primary} />
      </View>
      <Text style={styles.sectionTitle}>{title}</Text>
    </View>
    <View style={styles.sectionBody}>{children}</View>
  </View>
);

const Para = ({ children }) => (
  <Text style={styles.para}>{children}</Text>
);

const Bullet = ({ children }) => (
  <View style={styles.bulletRow}>
    <View style={styles.bulletDot} />
    <Text style={styles.bulletText}>{children}</Text>
  </View>
);

// ── Screen ─────────────────────────────────────────────────────────────────────
const PrivacyPolicyScreen = ({ navigation }) => {
  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor={Colors.primaryDark} />

      {/* Header */}
      <LinearGradient colors={[Colors.primaryDark, Colors.primary]} style={styles.header}>
        <View style={styles.headerRow}>
          <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
            <Ionicons name="arrow-back" size={22} color={Colors.white} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Privacy Policy</Text>
          <View style={{ width: 40 }} />
        </View>
        <Text style={styles.headerSub}>Effective Date: March 2026</Text>
      </LinearGradient>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>

        {/* Intro Card */}
        <View style={styles.introCard}>
          <Ionicons name="shield-checkmark" size={32} color={Colors.primary} />
          <Text style={styles.introTitle}>Your Privacy Matters</Text>
          <Text style={styles.introPara}>
            The Price and Stock Alert Application ("PriceAlert", "the App", "we", "us") is
            committed to protecting your personal information. This Privacy Policy explains
            how we collect, use, store, and safeguard your data when you use our application.
          </Text>
          <View style={styles.academicBadge}>
            <Ionicons name="school-outline" size={14} color={Colors.accent} />
            <Text style={styles.academicText}>
              This is an academic capstone project developed for educational purposes only.
            </Text>
          </View>
        </View>

        {/* 1. Information We Collect */}
        <Section icon="document-text-outline" title="1. Information We Collect">
          <Para>We collect the following types of information when you use the App:</Para>

          <Text style={styles.subHeading}>a. Account Information</Text>
          <Bullet>Full name and email address (provided during registration)</Bullet>
          <Bullet>Password stored using bcrypt hashing — never stored in plain text</Bullet>
          <Bullet>Profile photo (optional, uploaded by you)</Bullet>

          <Text style={styles.subHeading}>b. Watchlist Data</Text>
          <Bullet>Product URLs from Shopee and Lazada that you add to your watchlist</Bullet>
          <Bullet>Product names, current prices, and target prices you set per item</Bullet>
          <Bullet>Your notification preferences per product</Bullet>

          <Text style={styles.subHeading}>c. Usage & Technical Data</Text>
          <Bullet>Price history records generated by the monitoring system</Bullet>
          <Bullet>Notification logs (price drops, stock changes, target price alerts)</Bullet>
          <Bullet>
            Expo push notification token — used only to deliver alerts to your device
          </Bullet>
          <Bullet>
            Session tokens via Laravel Sanctum (expire automatically upon logout or session end)
          </Bullet>
        </Section>

        {/* 2. How We Use Your Information */}
        <Section icon="settings-outline" title="2. How We Use Your Information">
          <Para>
            We use your information solely to provide the core features of the App. We do
            NOT use your data for advertising, profiling, or any commercial purpose.
          </Para>
          <Bullet>To create and manage your user account</Bullet>
          <Bullet>To monitor product prices and stock status on your behalf</Bullet>
          <Bullet>
            To send alerts when prices drop, targets are reached, or stock changes
          </Bullet>
          <Bullet>To display your price history and savings summary</Bullet>
          <Bullet>To allow you to share your watchlist with others via a unique link</Bullet>
          <Bullet>
            To enable administrators to manage users and products within the system
          </Bullet>
        </Section>

        {/* 3. Data Storage and Security */}
        <Section icon="lock-closed-outline" title="3. Data Storage and Security">
          <Para>
            Your data is stored in a secure local database on the application server. As an
            academic project, the app runs on a local development server (XAMPP). No data is
            transmitted to external servers or third-party services.
          </Para>
          <Bullet>Passwords hashed with bcrypt — never stored in plain text</Bullet>
          <Bullet>
            All API requests authenticated via Bearer tokens (Laravel Sanctum)
          </Bullet>
          <Bullet>
            Profile photos stored in a protected server directory, not publicly indexed
          </Bullet>
          <Bullet>
            Admin access is restricted to user and product management only
          </Bullet>
        </Section>

        {/* 4. Third-Party Services — NEW */}
        <Section icon="globe-outline" title="4. Third-Party Services">
          <Para>
            To monitor products on your watchlist, the App accesses publicly available
            product pages on Shopee and Lazada. We do not interact with their APIs on your
            behalf, create accounts on these platforms, or store any credentials related to
            them. Only the product URL you provide is used to retrieve publicly visible
            price and stock data.
          </Para>
          <Para>
            We are not affiliated with, endorsed by, or partnered with Shopee or Lazada.
            Use of their platforms is subject to their own respective terms of service and
            privacy policies.
          </Para>
        </Section>

        {/* 5. Data Sharing */}
        <Section icon="share-social-outline" title="5. Data Sharing">
          <Para>
            We do not sell, trade, or share your personal information with any third
            parties. The only exceptions are:
          </Para>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Shared Watchlist Feature</Text>
            {' — '}If you choose to generate a share link, your watchlist (product names,
            prices, and stock status) becomes viewable to anyone with that link. This is
            entirely opt-in and within your control.
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Admin Access</Text>
            {' — '}System administrators can view user account information and product data
            for system management purposes only, and are bound by the same data privacy
            obligations as this policy.
          </Bullet>
        </Section>

        {/* 6. Your Rights under RA 10173 — EXPANDED */}
        <Section icon="person-outline" title="6. Your Rights under RA 10173">
          <Para>
            Under the Data Privacy Act of 2012 (Republic Act No. 10173) of the Philippines,
            you have the following rights as a data subject:
          </Para>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Be Informed</Text>
            {' — '}You are informed of how your data is collected, used, and stored, as
            described in this Privacy Policy
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Access</Text>
            {' — '}You can view all your personal data within the app (profile, watchlist,
            notifications)
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Rectification</Text>
            {' — '}You can update your name, email, and password at any time via
            Profile → Edit Profile
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Erasure / Blocking</Text>
            {' — '}You can remove products from your watchlist at any time. Account
            deletion can be requested from an administrator
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Object</Text>
            {' — '}You may opt out of specific notification types via Notification
            Preferences
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Data Portability</Text>
            {' — '}Your watchlist can be shared via a read-only link, allowing you to
            reference your data externally
          </Bullet>
          <Bullet>
            <Text style={{ fontWeight: FontWeight.bold }}>Right to Damages</Text>
            {' — '}You may seek compensation if your rights under the Data Privacy Act
            are violated
          </Bullet>
        </Section>

        {/* 7. Data Retention */}
        <Section icon="time-outline" title="7. Data Retention">
          <Para>
            Your data is retained for as long as your account is active in the system.
            Specifically:
          </Para>
          <Bullet>Account data is retained until deleted by an administrator</Bullet>
          <Bullet>
            Price history records are retained for trend analysis while your account is active
          </Bullet>
          <Bullet>
            Notification records are retained for reference and history purposes
          </Bullet>
          <Bullet>
            Authentication tokens expire automatically upon logout or session end
          </Bullet>
        </Section>

        {/* 8. Cookies and Tracking */}
        <Section icon="eye-off-outline" title="8. Cookies and Tracking">
          <Para>
            The PriceAlert App does not use cookies, tracking pixels, or any analytics
            tools. We do not track your behavior across other websites or applications.
          </Para>
          <Para>
            The only monitoring performed within the app is price and stock checking for
            products you have explicitly added to your watchlist.
          </Para>
        </Section>

        {/* 9. Children's Privacy */}
        <Section icon="happy-outline" title="9. Children's Privacy">
          <Para>
            The PriceAlert App is not directed at children under the age of 13. We do not
            knowingly collect personal information from children. If you believe a child
            has provided personal information through the app, please contact the
            development team immediately.
          </Para>
        </Section>

        {/* 10. Changes to This Policy */}
        <Section icon="refresh-outline" title="10. Changes to This Policy">
          <Para>
            As this is an academic project, this Privacy Policy may be updated to reflect
            changes in the application's features or requirements. Any significant changes
            will be reflected in the effective date at the top of this document. Continued
            use of the App after changes are posted constitutes your acceptance of the
            updated policy.
          </Para>
        </Section>

        {/* 11. Contact */}
        <Section icon="mail-outline" title="11. Contact Information">
          <Para>
            If you have any questions, concerns, or requests regarding this Privacy Policy
            or your personal data, please contact the development team through your
            institution's academic channels.
          </Para>
          <View style={styles.contactCard}>
            <Ionicons name="school-outline" size={20} color={Colors.primary} />
            <View style={{ flex: 1 }}>
              <Text style={styles.contactLabel}>Price and Stock Alert Application</Text>
              <Text style={styles.contactSub}>Capstone Project — Academic Use Only</Text>
              <Text style={styles.contactSub}>Version 1.0.0 · March 2026</Text>
            </View>
          </View>
        </Section>

        {/* Footer */}
        <View style={styles.footer}>
          <Ionicons name="shield-checkmark" size={16} color={Colors.success} />
          <Text style={styles.footerText}>
            This privacy policy is aligned with standard data privacy practices and the
            Data Privacy Act of 2012 (Republic Act No. 10173) of the Philippines. As an
            academic project, it demonstrates good-faith compliance with applicable data
            privacy principles.
          </Text>
        </View>

      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container:      { flex: 1, backgroundColor: Colors.bg },
  header:         { paddingTop: 50, paddingBottom: Spacing.xl, paddingHorizontal: Spacing.lg },
  headerRow:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.sm },
  backBtn:        { width: 40, height: 40, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.15)', justifyContent: 'center', alignItems: 'center' },
  headerTitle:    { color: Colors.white, fontSize: FontSize.lg, fontWeight: FontWeight.bold },
  headerSub:      { color: 'rgba(255,255,255,0.7)', fontSize: FontSize.xs, textAlign: 'center' },
  content:        { padding: Spacing.lg, paddingBottom: 48, gap: Spacing.md },

  // Intro
  introCard:      { backgroundColor: Colors.white, borderRadius: Radius.xl, padding: Spacing.xl, alignItems: 'center', gap: Spacing.sm, ...Shadow.default },
  introTitle:     { fontSize: FontSize.lg, fontWeight: FontWeight.black, color: Colors.text, textAlign: 'center' },
  introPara:      { fontSize: FontSize.sm, color: Colors.textMuted, textAlign: 'center', lineHeight: 20 },
  academicBadge:  { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Colors.accent + '15', borderRadius: Radius.md, padding: Spacing.md, marginTop: Spacing.sm },
  academicText:   { flex: 1, fontSize: FontSize.xs, color: Colors.accent, fontWeight: FontWeight.semiBold, lineHeight: 16 },

  // Section
  section:        { backgroundColor: Colors.white, borderRadius: Radius.xl, padding: Spacing.lg, ...Shadow.sm, gap: Spacing.sm },
  sectionHeader:  { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.xs },
  sectionIconBox: { width: 34, height: 34, borderRadius: Radius.sm, backgroundColor: Colors.primary + '15', justifyContent: 'center', alignItems: 'center' },
  sectionTitle:   { fontSize: FontSize.base, fontWeight: FontWeight.black, color: Colors.text, flex: 1 },
  sectionBody:    { gap: Spacing.sm },
  subHeading:     { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Colors.text, marginTop: Spacing.sm, marginBottom: 2 },
  para:           { fontSize: FontSize.sm, color: Colors.textMuted, lineHeight: 20 },
  bulletRow:      { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm, paddingLeft: Spacing.sm },
  bulletDot:      { width: 6, height: 6, borderRadius: 3, backgroundColor: Colors.primary, marginTop: 7, flexShrink: 0 },
  bulletText:     { flex: 1, fontSize: FontSize.sm, color: Colors.textMuted, lineHeight: 20 },

  // Contact
  contactCard:    { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, backgroundColor: Colors.primary + '10', borderRadius: Radius.md, padding: Spacing.md, marginTop: Spacing.sm },
  contactLabel:   { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Colors.text },
  contactSub:     { fontSize: FontSize.xs, color: Colors.textMuted, marginTop: 2 },

  // Footer
  footer:         { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm, backgroundColor: Colors.success + '15', borderRadius: Radius.md, padding: Spacing.md, borderWidth: 1, borderColor: Colors.success + '30' },
  footerText:     { flex: 1, fontSize: FontSize.xs, color: Colors.success, lineHeight: 18, fontWeight: FontWeight.semiBold },
});

export default PrivacyPolicyScreen;